### ISSUE TITLE
No code and issue with minero.pw

### ISSUE THREAD

**Issue by dennym** [cazala/minero#3]
Only can see Readme is this intended? Also have the issue that I can't get in your site since my ether address doesn't st get accepted although it gets used quite well.

**Comment by kolpav** [comment]
You can view the code by clicking links in 
> The proxy and the API are both hosted in...

I think the only thing that is not open sourced is the UI

**Comment by cazala** [comment]
The sources are not in the repo but the source maps are there, so if you open http://minero.pw and open the console -> resources you will be able to browse the source @kolpav (:

**Comment by cazala** [comment]
@dennym you need to mine at least 1 accepted hash before your stats appear in the page

**Comment by dennym** [comment]
Yeah I figured it out. I was on mobile and didn't see the scroll down. So I checked github to figure out how it works but now I know :D
