### ISSUE TITLE
[Error] Fetch API cannot load due to access control checks.

### ISSUE THREAD

**Issue by sputn1k** [cazala/minero#4]
Getting multiple console errors. When I hit the start button:

`[Error] Fetch API cannot load http://minero.pw/cryptonight.wasm due to access control checks.`

**Comment by cazala** [comment]
Try using [CoinHive Proxy](https://coinhive-proxy.party/), minero.pw is deprecated until i figure out a way to fix mineXMR.com Worker API issues
