### ISSUE TITLE
hashes stuck, balance possibly not updating.

### ISSUE THREAD

**Issue by Heldex** [cazala/minero#7]
hello, is the balance stuck or something.
18ugMnMjiLDK33xKb5fPGCzAPpPtxRQhn1
im using node to mine + inside 1 website and the balance is not updating
is everything working backend?

**Comment by cazala** [comment]
this has been reported by #5, I'm working on a solution for this, i'll try to have it live by the end of the weekend or at some point during the week. I'll keep you posted.

**Comment by Heldex** [comment]
btw, this might be the problem minexmr said when using more than ~1000 worker IDs, this page will become unresponsive - updates are in progress

**Comment by cazala** [comment]
There weren't that many miners, not even close..

This is the solution I came up with: [CoinHive Proxy](https://coinhive-proxy.party)
