### ISSUE TITLE
On minero.pw I can't see any progress.

### ISSUE THREAD

**Issue by jackeown** [cazala/minero#8]
**"Not Found
You need to mine at least 1 accepted hash in order to show up here."**

the above message shows up when I try to mine to my Dogecoin address: DKNYNDLTJLsjcG6CZzicLVdst69y4JLQ91

I made sure I let it run for about an hour and the stats given said it had many accepted hashes even...it's hosted at http://www.jackmckeown.com/mining/ if you would be willing to take a look.

I have commented out in the source code for that page my ETH mining which worked before I tried Dogecoin. Is there any reason for this you can think of?

Thanks,
Jack McKeown

**Comment by cazala** [comment]
Hi, it has been reported #5. There's not much I can do, it seems like mineXMR.com API is broken, I'm shutting down this soon. But I just finished a tool to workaround AdBlock issues and allow users to mine on different pools if they want to, [CoinHive Proxy](https://coinhive-proxy.party).
