### ISSUE TITLE
Phantom hashes

### ISSUE THREAD

**Issue by rub1e** [cazala/minero#9]
I was playing around with this yesterday - couldn't get it to work in the browser (stuck at "Connecting to pool..."). 

I ran it in the terminal for I guess a couple of hours, then stopped it with about 20k accepted hashes. I then shut down the computer.

This morning (15 mins ago), I went to minero.pw and it says I have **2.4M accepted hashes**! 

Hard to see how this could have happened unless it actually did connect to a pool in the browser and it continued running at the same time as the terminal. This seems quite unlikely, and either way the computer has been shut down for the past 8 hours at least - 2.4M hashes just seems totally impossible for my laptop.

Any ideas?

**Comment by cazala** [comment]
It has been reported that minero.pw screws up with the hashes (it mixes the user hashes). I created a tool that seems to be working better so far: [CoinHive Proxy](https://coinhive-proxy.party/)

**Comment by rub1e** [comment]
@cazala yes, I saw - just wanted to report in case it helped diagnose the problem. (It's back to usual now, just checked.)

Closing now, thanks!
